[build]
  publish = "./public"
  command = "npm run build"

[build.environment]
  ELM_HOME = "$NETLIFY_BUILD_BASE/cache/elm"
  NO_ELM_TOOLING_INSTALL = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200